require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DataboxesController do

  # This should return the minimal set of attributes required to create a valid
  # Databox. As you add validations to Databox, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DataboxesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all databoxes as @databoxes" do
      databox = Databox.create! valid_attributes
      get :index, {}, valid_session
      assigns(:databoxes).should eq([databox])
    end
  end

  describe "GET show" do
    it "assigns the requested databox as @databox" do
      databox = Databox.create! valid_attributes
      get :show, {:id => databox.to_param}, valid_session
      assigns(:databox).should eq(databox)
    end
  end

  describe "GET new" do
    it "assigns a new databox as @databox" do
      get :new, {}, valid_session
      assigns(:databox).should be_a_new(Databox)
    end
  end

  describe "GET edit" do
    it "assigns the requested databox as @databox" do
      databox = Databox.create! valid_attributes
      get :edit, {:id => databox.to_param}, valid_session
      assigns(:databox).should eq(databox)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Databox" do
        expect {
          post :create, {:databox => valid_attributes}, valid_session
        }.to change(Databox, :count).by(1)
      end

      it "assigns a newly created databox as @databox" do
        post :create, {:databox => valid_attributes}, valid_session
        assigns(:databox).should be_a(Databox)
        assigns(:databox).should be_persisted
      end

      it "redirects to the created databox" do
        post :create, {:databox => valid_attributes}, valid_session
        response.should redirect_to(Databox.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved databox as @databox" do
        # Trigger the behavior that occurs when invalid params are submitted
        Databox.any_instance.stub(:save).and_return(false)
        post :create, {:databox => { "title" => "invalid value" }}, valid_session
        assigns(:databox).should be_a_new(Databox)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Databox.any_instance.stub(:save).and_return(false)
        post :create, {:databox => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested databox" do
        databox = Databox.create! valid_attributes
        # Assuming there are no other databoxes in the database, this
        # specifies that the Databox created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Databox.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => databox.to_param, :databox => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested databox as @databox" do
        databox = Databox.create! valid_attributes
        put :update, {:id => databox.to_param, :databox => valid_attributes}, valid_session
        assigns(:databox).should eq(databox)
      end

      it "redirects to the databox" do
        databox = Databox.create! valid_attributes
        put :update, {:id => databox.to_param, :databox => valid_attributes}, valid_session
        response.should redirect_to(databox)
      end
    end

    describe "with invalid params" do
      it "assigns the databox as @databox" do
        databox = Databox.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Databox.any_instance.stub(:save).and_return(false)
        put :update, {:id => databox.to_param, :databox => { "title" => "invalid value" }}, valid_session
        assigns(:databox).should eq(databox)
      end

      it "re-renders the 'edit' template" do
        databox = Databox.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Databox.any_instance.stub(:save).and_return(false)
        put :update, {:id => databox.to_param, :databox => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested databox" do
      databox = Databox.create! valid_attributes
      expect {
        delete :destroy, {:id => databox.to_param}, valid_session
      }.to change(Databox, :count).by(-1)
    end

    it "redirects to the databoxes list" do
      databox = Databox.create! valid_attributes
      delete :destroy, {:id => databox.to_param}, valid_session
      response.should redirect_to(databoxes_url)
    end
  end

end
